"""Localization mode: FAST-LIO + MCL 3DL + ESKF fusion + 3D nav stack.

Prereq: pose graph generated by mapping mode.
Tunables: src/dddnav_bringup/config/runtime.yaml (timing, lidar mount, etc.)
"""
import os
import sys
from ament_index_python.packages import get_package_share_directory
from launch import LaunchDescription
from launch_ros.actions import Node
from launch.actions import DeclareLaunchArgument, TimerAction, ExecuteProcess
from launch.substitutions import LaunchConfiguration

sys.path.insert(0, os.path.join(get_package_share_directory('dddnav_bringup'), 'launch'))
import bringup_paths


def generate_launch_description():
    rt = bringup_paths.load_runtime()
    d = rt['delays']
    m = rt['lidar_mount']
    ip = rt['initial_pose']

    livox_share    = get_package_share_directory('livox_ros_driver2')
    fast_lio_share = get_package_share_directory('fast_lio')
    p2p_share      = get_package_share_directory('p2p_move_base')
    bringup_share  = get_package_share_directory('dddnav_bringup')
    pose_fusion_yaml = os.path.join(
        get_package_share_directory('dddnav_pose_fusion'), 'config', 'pose_fusion.yaml')
    LIVOX_CONFIG = os.path.join(livox_share, 'config', 'MID360_config.json')

    initial_pose_msg = (
        f"{{header: {{frame_id: 'map'}}, "
        f"pose: {{pose: {{position: {{x: {ip['x']}, y: {ip['y']}, z: {ip['z']}}}, "
        f"orientation: {{w: 1.0}}}}}}}}"
    )

    return LaunchDescription([
        DeclareLaunchArgument('fastlio_config',
            default_value=os.path.join(fast_lio_share, 'config', 'mid360_pc2.yaml')),
        DeclareLaunchArgument('nav_config',
            default_value=os.path.join(p2p_share, 'config', 'mid360_localization.yaml')),
        DeclareLaunchArgument('rviz_config',
            default_value=os.path.join(bringup_share, 'rviz', 'localization.rviz')),

        # Livox Mid360 driver
        Node(package='livox_ros_driver2', executable='livox_ros_driver2_node',
             name='livox_lidar_publisher', output='screen',
             parameters=[{
                 'xfer_format': 0, 'multi_topic': 0, 'data_src': 0,
                 'publish_freq': float(rt['livox_publish_freq']),
                 'output_data_type': 0,
                 'frame_id': 'livox_frame',
                 'user_config_path': LIVOX_CONFIG,
             }]),

        # base_link -> livox_frame mount (edit lidar_mount in runtime.yaml)
        Node(package='tf2_ros', executable='static_transform_publisher',
             name='sensor2baselink',
             arguments=[str(m['x']), str(m['y']), str(m['z']),
                        str(m['yaw']), str(m['pitch']), str(m['roll']),
                        'base_link', 'livox_frame']),

        # Livox -> LIO-SAM/XYZI bridge (C++)
        TimerAction(period=d['bridges'], actions=[
            Node(package='dddnav_utils', executable='livox_pc2_to_liosam',
                 name='livox_pc2_to_liosam', output='screen',
                 parameters=[{'input_topic': '/livox/lidar',
                              'liosam_output_topic': '/livox/lidar_liosam',
                              'xyzi_output_topic': '/livox/lidar_liosam_xyzi'}]),
        ]),

        # FAST-LIO2 (publishes /Odometry, owns odom -> base_link TF)
        TimerAction(period=d['bridges'], actions=[
            Node(package='fast_lio', executable='fastlio_mapping',
                 name='fast_lio', output='screen',
                 parameters=[LaunchConfiguration('fastlio_config')]),
        ]),

        TimerAction(period=d['rviz'], actions=[
            Node(package='rviz2', executable='rviz2', name='rviz2', output='screen',
                 arguments=['-d', LaunchConfiguration('rviz_config')]),
        ]),

        # MCL 3DL — both TF flags off; pose_fusion owns map -> odom and
        # FAST-LIO owns odom -> base_link.
        TimerAction(period=d['mcl_3dl'], actions=[
            Node(package='mcl_3dl', executable='mcl_3dl', output='screen',
                 parameters=[LaunchConfiguration('nav_config'),
                             bringup_paths.pose_graph_overlay(),
                             {'publish_tf': False, 'publish_odom_tf': False}],
                 remappings=[('odom', '/Odometry'),
                             ('laser_cloud_sharp', '/laser_cloud_sharp'),
                             ('laser_cloud_less_sharp', '/laser_cloud_less_sharp'),
                             ('laser_cloud_flat', '/laser_cloud_flat'),
                             ('laser_cloud_less_flat', '/laser_cloud_less_flat')]),
        ]),

        # ESKF fusion: 100Hz /odom_filtered + map -> odom TF
        TimerAction(period=d['pose_fusion'], actions=[
            Node(package='dddnav_pose_fusion', executable='pose_fusion_node',
                 name='pose_fusion', output='screen',
                 parameters=[pose_fusion_yaml]),
        ]),

        # MCL feature extraction
        TimerAction(period=d['mcl_feature'], actions=[
            Node(package='dddnav_mcl_feature', executable='mcl_feature', output='screen',
                 parameters=[LaunchConfiguration('nav_config')],
                 remappings=[('/lslidar_point_cloud', '/livox/lidar_liosam_xyzi'),
                             ('/odom', '/Odometry')]),
        ]),

        # Bootstrap initial pose (override at runtime via /initial_3d_pose).
        TimerAction(period=d['initial_pose'], actions=[
            ExecuteProcess(cmd=[
                'ros2', 'topic', 'pub', '--once', '/initial_3d_pose',
                'geometry_msgs/msg/PoseWithCovarianceStamped',
                initial_pose_msg,
            ], output='screen'),
        ]),

        TimerAction(period=d['global_planner'], actions=[
            Node(package='global_planner', executable='global_planner_node', output='screen',
                 parameters=[LaunchConfiguration('nav_config')]),
        ]),

        TimerAction(period=d['move_base'], actions=[
            Node(package='p2p_move_base', executable='p2p_move_base_node', output='screen',
                 parameters=[LaunchConfiguration('nav_config')]),
        ]),
        TimerAction(period=d['clicked_goal'], actions=[
            Node(package='p2p_move_base', executable='clicked2goal.py',
                 name='clicked2goal', output='screen'),
        ]),
    ])
