"""Localization mode: FAST-LIO + MCL 3DL + ESKF fusion + 3D nav stack.

Prereq: pose graph generated by mapping mode (under
``share/dddnav_bringup/map`` after install).
Tunables: ``src/dddnav_bringup/config/runtime.yaml``.
"""

import os
import sys

from ament_index_python.packages import get_package_share_directory
from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument
from launch.substitutions import LaunchConfiguration

sys.path.insert(0, os.path.join(
    get_package_share_directory('dddnav_bringup'), 'launch'))
import bringup_paths
import common_nodes


def generate_launch_description():
    bringup_dir       = get_package_share_directory('dddnav_bringup')
    fast_lio_dir      = get_package_share_directory('fast_lio')
    pose_fusion_yaml  = os.path.join(
        get_package_share_directory('dddnav_pose_fusion'),
        'config', 'pose_fusion.yaml')

    rt = bringup_paths.load_runtime()

    fastlio_config = LaunchConfiguration('fastlio_config')
    rviz_config    = LaunchConfiguration('rviz_config')

    declare_fastlio_config_cmd = DeclareLaunchArgument(
        'fastlio_config',
        default_value=os.path.join(fast_lio_dir, 'config', 'mid360_pc2.yaml'),
        description='Full path to the FAST-LIO yaml',
    )
    declare_rviz_config_cmd = DeclareLaunchArgument(
        'rviz_config',
        default_value=os.path.join(bringup_dir, 'rviz', 'localization.rviz'),
        description='Full path to the RVIZ config file',
    )

    nav_profile_decl, nav_profile_resolve = bringup_paths.nav_profile_argument(
        default_profile='mid360_localization')
    nav_config_param_files = [
        bringup_paths.nav_base_yaml(),
        LaunchConfiguration('nav_config'),
        bringup_paths.pose_graph_overlay(),
    ]

    ld = LaunchDescription([
        declare_fastlio_config_cmd,
        declare_rviz_config_cmd,
        nav_profile_decl,
        nav_profile_resolve,
    ])

    for action in common_nodes.lidar_driver_and_tf(rt):
        ld.add_action(action)
    for action in common_nodes.lidar_front_end(rt, fastlio_config):
        ld.add_action(action)
    for action in common_nodes.localization_stack(
            rt, nav_config_param_files, pose_fusion_yaml):
        ld.add_action(action)
    for action in common_nodes.nav_stack(rt, nav_config_param_files):
        ld.add_action(action)

    ld.add_action(common_nodes.rviz_action(rt, rviz_config))
    return ld
