FROM dddnav:x64

#install ROS2-based gz dependencies
RUN apt update && apt install -y ros-humble-gazebo-ros2-control
RUN apt install -y ros-humble-xacro
RUN apt install -y ros-humble-robot-localization
RUN apt install -y ros-humble-ros2-controllers
RUN apt install -y ros-humble-ros2-control
RUN apt install -y ros-humble-velodyne
RUN apt install -y ros-humble-velodyne-gazebo-plugins
RUN apt-get install -y ros-humble-velodyne-description

# create ws_gz and clone repo
WORKDIR /
RUN mkdir -p ws_gz/src && \
    cd ws_gz/src && \
    git clone https://github.com/dfl-rlab/gz_quadbot.git

WORKDIR /ws_gz

CMD ["bash"]
